### ISSUE TITLE
a dummy Issue to upload images in Wiki

### ISSUE THREAD

**Issue by kyu-kim-kr** [kyu-kim-kr/baseball#1]

**Comment by kyu-kim-kr** [comment]
<img width="840" alt="스크린샷 2021-05-03 오후 5 54 28" src="https://user-images.githubusercontent.com/59721293/116861805-d7f19c80-ac57-11eb-8361-cfefb03a1cc8.png">

**Comment by kyu-kim-kr** [comment]
![스크린샷 2021-05-03 오후 6 03 06](https://user-images.githubusercontent.com/59721293/116861946-14bd9380-ac58-11eb-8925-d96c27589cfc.png)

**Comment by kyupid** [comment]
![2021-05-13_07-56-42](https://user-images.githubusercontent.com/59721293/118036556-d09d6200-b3c0-11eb-910e-8c90f6d9497f.jpg)
![2021-05-13_07-57-26](https://user-images.githubusercontent.com/59721293/118036594-deeb7e00-b3c0-11eb-9b18-335ab2e47891.jpg)

**Comment by kyupid** [comment]
![2021-05-14_18-11-11](https://user-images.githubusercontent.com/59721293/118229310-e6557900-b4df-11eb-8207-b640032f3eec.jpg)

<img width="862" alt="스크린샷 2021-05-14 오후 3 17 00" src="https://user-images.githubusercontent.com/59721293/118229895-e4d88080-b4e0-11eb-90ce-91c83d345a49.png">

![2021-05-14_18-19-34](https://user-images.githubusercontent.com/59721293/118229938-f588f680-b4e0-11eb-9701-b95382549b5c.jpg)

**Comment by kyupid** [comment]
<img width="872" alt="스크린샷 2021-05-14 오후 3 21 04" src="https://user-images.githubusercontent.com/59721293/118230142-4567bd80-b4e1-11eb-8b0f-41e9060575fe.png">
